/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class CrearSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form Crear
     */
    public CrearSala() {
        initComponents();
        this.setTitle("Crear Sala");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_numFila = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_numColuma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_tipoSala = new javax.swing.JComboBox<>();
        b_crearSala = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de Filas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));
        jPanel1.add(t_numFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 24, -1, -1));

        jLabel2.setText("Número de Columnas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, -1, -1));
        jPanel1.add(t_numColuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 64, -1, -1));

        jLabel3.setText("Tipo de Sala");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, -1, -1));

        c_tipoSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2D", "3D" }));
        jPanel1.add(c_tipoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 104, 64, -1));

        b_crearSala.setText("CREAR");
        jPanel1.add(b_crearSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 138, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crearSala;
    private javax.swing.JComboBox<String> c_tipoSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t_numColuma;
    private javax.swing.JTextField t_numFila;
    // End of variables declaration//GEN-END:variables
}
