
import Logica.Cine;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author pc
 */
public class ReservaClientes extends javax.swing.JInternalFrame {

    /**
     * Creat * Creates new form ReservaClientes es new form ReservaClientes
     */
    Cine elCine = General.elCine;

    public ReservaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fila = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Funsion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));
        getContentPane().add(fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 39, 150, -1));

        jLabel2.setText("Sala");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));
        getContentPane().add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 67, 150, -1));

        jLabel3.setText("Silla");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, -1, -1));
        getContentPane().add(fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 95, 41, -1));
        getContentPane().add(col, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 95, 41, -1));

        jButton1.setText("RESERVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 123, -1, -1));

        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 5, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 5, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!fila.getText().isEmpty() && !col.getText().isEmpty() && !user.getText().isEmpty()) {
            int f = Integer.parseInt(fila.getText());
            int c = Integer.parseInt(col.getText());
            int s = Integer.parseInt(sala.getText());
            boolean reserva = elCine.reservarSilla(s, title, f, c, user.getText());
            if (reserva == true) {
                JOptionPane.showMessageDialog(this, "Reserva exitosa", "Reservas", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(this, "LA SILLA ESTÁ OCUPADA, SELECCIONE OTRA", "SILLA OCUPADA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "LOS CAMPOS SON OBLIGATORIOS", "CAMPOS VACÍOS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField col;
    private javax.swing.JTextField fila;
    private javax.swing.JTextField fun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField sala;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
